### ISSUE TITLE
"No resources match" - might be inaccurate due to resource type comparison

### ISSUE THREAD

**Issue by kmcquade** [duo-labs/parliament#10]
This is related to #9, but I'm opening it up as a separate issue because I think #9 is a possible root cause, but this one is the symptom.

I ran Parliament on this policy:

https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_examples_aws_my-sec-creds-self-manage.html

And got this error:

```
INVALID - No resources match for iam:CreateVirtualMFADevice which requires a resource format of arn:*:iam::*:mfa/*/* for the resource mfa* - {'filepath': None}
```

Which I believe is inaccurate:

https://docs.aws.amazon.com/IAM/latest/UserGuide/list_identityandaccessmanagement.html#identityandaccessmanagement-resources-for-iam-policies

![image](https://user-images.githubusercontent.com/3422255/69497663-a21a8700-0ead-11ea-95aa-7ab371547f03.png)

**Comment by 0xdabbad00** [comment]
I believe Parliament is working correctly in this case, but that the docs are incorrect.  In the policy it contains a Resource of `arn:aws:iam::*:mfa/${aws:username}`, but the docs say the action `iam:CreateVirtualMFADevice` requires a resource of `arn:${Partition}:iam::${Account}:mfa/${Path}/${MfaTokenId}`.  So the the mismatch is with `${aws:username}` and `${Path}/${MfaTokenId}` where the latter (from the docs) requires there to be a `/`, but the policy does not.

My philosophy with Parliament is that I want it to check IAM policies against what is defined by the documentation, and if the documentation is incorrect then AWS should fix their docs as opposed to Parliament working around AWS's mistakes.  I've therefore submitted a ticket against the AWS docs at https://github.com/awsdocs/iam-user-guide/issues/161

**Comment by 0xdabbad00** [comment]
I had closed this, have decided instead to keep open issues like this open until AWS actually fixes their docs and I then cut a release of Parliament that takes this into consideration.  Thank you for reporting this.

**Comment by 0xdabbad00** [comment]
Someone from AWS commented on the ticket I filed against them that I am correct and they need to make changes, but they have not yet made those changes.

**Comment by 0xdabbad00** [comment]
I asked AWS for an update (via the ticket against the IAM user guide) and they said they are still working on it.

**Comment by 0xdabbad00** [comment]
I've asked AWS for an update on this again via the github ticket mentioned earlier in this thread.
