### ISSUE TITLE
Resource `*` policy generates a ton of findings

### ISSUE THREAD

**Issue by zscholl** [duo-labs/parliament#118]
I was testing out an example policy:
```json
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "Stmt1589555570362",
      "Action": "guardduty:*",
      "Effect": "Allow",
      "Resource": "*"
    }
  ]
}
```

Calling this with `parliament --file test.json` generates 52 findings that are exactly the same.

```bash
python parliament/cli.py --file test.json
LOW - Unnecessary use of Resource * -  - None - {'actions': ['guardduty:*'], 'filepath': 'test.json'}
LOW - Unnecessary use of Resource * -  - None - {'actions': ['guardduty:*'], 'filepath': 'test.json'}
LOW - Unnecessary use of Resource * -  - None - {'actions': ['guardduty:*'], 'filepath': 'test.json'}
LOW - Unnecessary use of Resource * -  - None - {'actions': ['guardduty:*'], 'filepath': 'test.json'}
LOW - Unnecessary use of Resource * -  - None - {'actions': ['guardduty:*'], 'filepath': 'test.json'}
LOW - Unnecessary use of Resource * -  - None - {'actions': ['guardduty:*'], 'filepath': 'test.json'}
LOW - Unnecessary use of Resource * -  - None - {'actions': ['guardduty:*'], 'filepath': 'test.json'}
LOW - Unnecessary use of Resource * -  - None - {'actions': ['guardduty:*'], 'filepath': 'test.json'}
...
```

I would expect there to only be a single finding. Not sure if this is a problem with the specific auditor. As a workaround I'm just going to unique the findings list.

**Comment by 0xdabbad00** [comment]
That is not good.  I'm guessing it is creating one finding for each action that is part of `guardduty:*` but that is not ideal.

**Comment by dgubitosi** [comment]
Yes!  It produces a finding for each "expanded" action from that wildcard.  I recently had to rationalize a similar situation where I had multiple wildcarded actions in a policy and I got hundreds of those.  I wrote a simple tool to parse through the iam_definition.json file and pick out all the relevant actions to confirm this is exactly what it was doing.

**Comment by dgubitosi** [comment]
@zscholl I just started a fork that only reports RESOURCE_STAR once per statement regardless of the number of actions, and has Sid tracking to improve the location field for findings. I'm still testing it thoroughly before opening a PR though.

**Comment by 0xdabbad00** [comment]
This is related to #117

**Comment by 0xdabbad00** [comment]
#128 had resolved this
