### ISSUE TITLE
AttributeError when Resource uses Sub

### ISSUE THREAD

**Issue by michael-k** [duo-labs/parliament#120]
Minimal example:

```json
{
    "Statement": [
        {
            "Action": [
                "ssm:PutParameter"
            ],
            "Effect": "Allow",
            "Resource": [
                {"Fn::Sub": "arn:aws:ssm:*:${AWS::AccountId}:*"}
            ]
        }
    ],
    "Version": "2012-10-17"
}
```

Checking this file fails with an AttributeError:

```
$ parliament --file test.json
Traceback (most recent call last):
  File "/usr/local/bin/parliament", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/parliament/cli.py", line 299, in main
    policy = analyze_policy_string(
  File "/usr/local/lib/python3.8/site-packages/parliament/__init__.py", line 67, in analyze_policy_string
    policy.analyze(
  File "/usr/local/lib/python3.8/site-packages/parliament/policy.py", line 240, in analyze
    stmt = Statement(stmt_json)
  File "/usr/local/lib/python3.8/site-packages/parliament/statement.py", line 277, in __init__
    if not self.analyze_statement():
  File "/usr/local/lib/python3.8/site-packages/parliament/statement.py", line 757, in analyze_statement
    parts = resource.split(":")
AttributeError: 'dict' object has no attribute 'split'
```

Sub: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-sub.html

**Comment by 0xdabbad00** [comment]
`Fn::Sub` is a CloudFormation concept and not an IAM concept, so this is out of scope for Parliament. You would need to have CloudFormation create the final policy somehow and then run it through Parliament.

**Comment by michael-k** [comment]
So you're not interested in a PR that handles the basic use cases (`${AWS::Region}` and `${AWS::AccountId}`)?  I would like to check the policies (or at least the majority of them) before deploying them and not afterwards.

How about responding with a helpful error message instead of ignoring the AttributeError?

**Comment by 0xdabbad00** [comment]
I do not think I would not a PR to make Parliament handle CloudFormation. I want to avoid expanding the scope of the project as I already struggle to keep up with the projects I maintain as it is.

Having a more helpful error message here and avoiding Parliament from crashing would be good though.
