### ISSUE TITLE
False negative: Malformed resource when using CreateChangeSet together with resource type transform

### ISSUE THREAD

**Issue by michael-k** [duo-labs/parliament#122]
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-iam-template.html#resource-level-permissions mentions this example:

```json
{
    "Version": "2012-10-17",
    "Statement": [{
        "Effect": "Allow",
        "Action": [
            "cloudformation:CreateChangeSet"
        ],
        "Resource": "arn:aws:cloudformation:us-west-2:aws:transform/Serverless-2016-10-31"
    }]
}
```

When linting this with parliament, the following medium issue is reported:

```
$ parliament --file test.json
MEDIUM - Invalid ARN - Malformed resource, should have the form
arn:partition:service:region:account:id - Account expected to be of form
like 123456789012 -
{
  'string': 'arn:aws:cloudformation:us-west-2:aws:transform/Serverless-2016-10-31',
  'filepath': 'test.json'
}
```

**Comment by 0xdabbad00** [comment]
I believe Parliament is behaving correctly here and that AWS has a mistake in their docs.  Have you tested that policy works @michael-k ?

**Comment by michael-k** [comment]
> I believe Parliament is behaving correctly here and that AWS has a mistake in their docs.

Yeah, I believe so too and reported it via their feedback form.  However I missed the section in your readme about how `iam_definition.json` is generated/updated and reported it also here to make sure.

I'm closing this in favor of the bug report at AWS.

> Have you tested that policy works

I believe it does.  We're using it production for a while now.
