### ISSUE TITLE
inline policies not being assessed with "get-account-authorization-details"

### ISSUE THREAD

**Issue by tekdj7** [duo-labs/parliament#125]
inline policies for Roles not being assessed with "get-account-authorization-details" argument, even when giving it the whole account-authorization details, as shown below:
  - aws iam get-account-authorization-details > test.json
  - parliament --auth-details-file test.json > results.txt

**Comment by 0xdabbad00** [comment]
Inline policies appear to be taken into account in my own testing.  The code that checks the inline policies is here: https://github.com/duo-labs/parliament/blob/a0beef0a07613787751ef8e5726dec476ebf6b44/parliament/cli.py#L285

**Comment by tekdj7** [comment]
Either I missed something, or it got fixed with the latest 5.0 version, not sure which.  But its working now.  Thanks!

**Comment by tekdj7** [comment]
Either I missed something, or it got fixed with the latest 5.0 version, not sure which.  But its working now.  Thanks!
