### ISSUE TITLE
CloudFormation Scope Question

### ISSUE THREAD

**Issue by ev3rl0ng** [duo-labs/parliament#141]
Hey all, use the tool pretty regularly and I find it handy. 

I'm interested in trying to add somewhat simple CloudFormation intrinsic function support for things like Joins and Subs, and the references to the AWS Pseudovars that could be filled with test data (123412341234 for AWS::AccountId, pick a region for AWS::Region, etc...) enough to run a check against structure. 

The note for CloudFormation in the tool states that it is currently out of scope, though. I wanted to kick up a discussion about whether it is out of scope because it's a complex feature to add, or whether it's truly 100% out of scope of the tool.

I look forward to your thoughts/ideas.

Thanks!

**Comment by 0xdabbad00** [comment]
There was a previous issue related to CloudFormation support in #120 and a PR to handle CloudFormation artifacts a little more gracefully in #124.

I want to keep Parliament focused on being an IAM policy linter and not become a CloudFormation linter.  I think it would make sense to have a separate tool convert CloudFormation code into a possibly valid IAM policy first.  The greater the scope of this project, the more overwhelming it would become to maintain, and this would result in it degrading its usefulness as there would be more bugs and tickets that I wouldn't have time to deal with, especially for things like CloudFormation related  linting that I am not interested in.

**Comment by ev3rl0ng** [comment]
That makes sense. That's the main thing that I was after.

Most of the things that I'm linting are ultimately embedded in CloudFormation and are made to be re-usable between accounts, so there's a lot of references to the pseudo-vars and use of intrinsic functions. Like I said, 100% valuable, just has a missing piece for me that I was looking to potentially add.

Will explore possibly writing a wrapper that will pass something over to parliament and perhaps post it back.

Thanks for the time and thoughts, @0xdabbad00 !
