### ISSUE TITLE
Policy variables in the resource element not supported

### ISSUE THREAD

**Issue by sckevmit** [duo-labs/parliament#146]
Hi, 
example policy:

```json
{
  "Version": "2012-10-17",
  "Statement": [
  {
      "Sid": "BucketAccess",
      "Effect": "Allow",
      "Action": [
        "s3:GetBucketLocation",
        "s3:GetBucketVersioning",
        "s3:GetEncryptionConfiguration",
        "s3:ListBucket",
        "s3:ListBucketMultipartUploads",
        "s3:ListBucketVersions"
      ],
      "Resource": "arn:aws:s3::bucket-for-client-${aws:PrincipalTag/Namespace}-*"
    }
]
}
```
Policy variable ${aws:PrincipalTag/Namespace} causes:
```json
{
    "description": "",
    "detail": [
        {
            "action": "s3:GetBucketLocation",
            "required_format": "arn:*:s3:::*"
        },
        {
            "action": "s3:GetBucketVersioning",
            "required_format": "arn:*:s3:::*"
        },
        {
            "action": "s3:GetEncryptionConfiguration",
            "required_format": "arn:*:s3:::*"
        },
        {
            "action": "s3:ListBucket",
            "required_format": "arn:*:s3:::*"
        },
        {
            "action": "s3:ListBucketMultipartUploads",
            "required_format": "arn:*:s3:::*"
        },
        {
            "action": "s3:ListBucketVersions",
            "required_format": "arn:*:s3:::*"
        }
    ],
    "issue": "RESOURCE_MISMATCH",
    "location": {
        "column": 3,
        "filepath": "main.json",
        "line": 4
    },
    "match": true,
    "severity": "MEDIUM",
    "title": "No resources match for the given action"
}
```

Maybe extending this condition https://github.com/duo-labs/parliament/blob/main/parliament/__init__.py#L118 by some regexp will be good enough for start ? ;) ( ex. (?P<Variable>\${aws:.*}) )

Take care!

**Comment by 0xdabbad00** [comment]
Looks like you are missing a colon.  S3 bucket resources are of the form `arn:*:s3:::bucket`, but you have `arn:*:s3::bucket`.

After fixing that though, looks like there is an issue with Parliament.  For the documentation's ARN, I do a regex to clear out the variables:
https://github.com/duo-labs/parliament/blob/afb6930992e7c22b128b377ce0fd46fef9e1d1a8/parliament/__init__.py#L248

I guess something similar could be done for this variable (I'm not entirely sure what impact that might have on any other checks).  I'm marking this as a bug to be fixed, but unfortunately I don't expect to be able to dig into this for a while.
