### ISSUE TITLE
No way to simply ignore a rule?

### ISSUE THREAD

**Issue by alexharv074** [duo-labs/parliament#148]
I would like to ignore some of the rules. For example, I am getting RESOURCE_MISMATCH all over the place and I want to ignore this for now. Is this possible?

**Comment by 0xdabbad00** [comment]
You can set a config override file as described here[1] and set the severity of `RESOURCE_MISTMATCH` to `mute`. Beware of recent issues identified with the config override if you try to use more advanced capabilities of it, as described here[2]

[1] https://github.com/duo-labs/parliament#custom-config-file
[2] https://github.com/duo-labs/parliament/issues/147

**Comment by alexharv074** [comment]
@0xdabbad00 But no way to do this if you try to use parliament as a library?

**Comment by 0xdabbad00** [comment]
You could call `override_config` like the CLI does here by passing it the path to a yaml file: https://github.com/duo-labs/parliament/blob/afb6930992e7c22b128b377ce0fd46fef9e1d1a8/parliament/cli.py#L227

The `config` structure that is modified is a global variable.
