### ISSUE TITLE
Option to turn off RESOURCE_MISMATCH checking

### ISSUE THREAD

**Issue by KevinHock** [duo-labs/parliament#172]
When scanning Terraform with Parliament, I'd like to replace certain TF vars that checkov can't handle in a pre-commit-ish way (remote state), with a dummy resource. The problem is, I'd have to recreate a lot of e.g. `get_privilege_info`, to, say, have a dummy bucket resource for s3 bucket actions, a dummy prefix resources for actions that operate on objects, and so on and so forth which is recreating a lot of parliament functionality e.g.

https://github.com/duo-labs/parliament/blob/3dcf32cdc80167f8bb51e9302fbff6ae7228738b/parliament/statement.py#L44

Here is where most of it happens, I propose we add a CLI flag to turn off this check.

https://github.com/duo-labs/parliament/blob/3dcf32cdc80167f8bb51e9302fbff6ae7228738b/parliament/statement.py#L874-L945

**Comment by KevinHock** [comment]
I could sort of understanding the argument that this is sort of me misusing the library, but I'd like to see how open you are to this :)


I cannot simply skip `parliament.config[enhanced_finding.issue]['group'] in ("INVALID"...)`, or something like that, as that would lead to false-negatives.

**Comment by 0xdabbad00** [comment]
This seems awkward as this was not the original intent of the library to be able to analyze anything other than IAM policies, but if it can be done simply by having a flag to skip some code, that seems reasonable.  You might be able to get away with just an `if flag: return True` somewhere, but alternatively you might try having `get_privilege_info` return a "fake" definition. For example, `s3:GetObject` requires a resource of `arn:*:s3:::*/*` so instead you might have your flag pretend like the docs said it could be `*`.

**Comment by KevinHock** [comment]
Thanks Scott! :)

**Comment by KevinHock** [comment]
Hmm, so I think this was made in error, I'm still getting the results I want, I was just making a mistake with my testing.
I'll go ahead and close this issue, sorry about that. 👍🏼 



Related to my mistake, would it make sense to make a PR to re-classify `RESOURCE_STAR` as `NOT_IDEAL`, instead of `MALFORMED`?

https://github.com/duo-labs/parliament/blob/da69dfd77981d8ef87923261980caa6eea9ae9a5/parliament/config.yaml#L113-L116

**Comment by 0xdabbad00** [comment]
Oh, yeah, that group should be changed. Happy to accept a PR for that.
