### ISSUE TITLE
ConsoleMe is using Parliament

### ISSUE THREAD

**Issue by castrapel** [duo-labs/parliament#178]
[ConsoleMe](http://github.com/Netflix/consoleme) is using Parliament for IAM inline policy linting. Here's an example:

https://demo.consolemeoss.com/policies/edit/844240725092/iamrole/ConsoleMeReadOnlyInstanceProfile

Can we have this added to the Readme, under "Projects that use Parliament"?

**Comment by steiza** [comment]
It has been added!
