### ISSUE TITLE
iam_definition.json doesn't capture all IAM actions

### ISSUE THREAD

**Issue by raghavkaul** [duo-labs/parliament#186]
iam_definition.json is missing several IAM actions which leads parliament to incorrectly report UNKNOWN_ACTION.

For example, `s3:GetBucketLifecycle` and `s3:GetBucketLifecycle` configuration are present here:

- https://docs.aws.amazon.com/AmazonS3/latest/API/API_GetBucketLifecycleConfiguration.html
- https://docs.aws.amazon.com/AmazonS3/latest/API/API_GetBucketLifecycle.html

... but not in the service-authorization documentation URL:
- https://docs.aws.amazon.com/service-authorization/latest/reference/list_amazons3.html

Likewise for `s3:HeadBucket`, which is not in the service-authorization page.
- https://docs.aws.amazon.com/AmazonS3/latest/API/API_HeadBucket.html

**Comment by kmcquade** [comment]
@raghavkaul - since Parliament depends on the service authorization page, I would suggest that AWS update the service authorization page to include those actions. Otherwise we get into the realm of maintaining our own list.

**Comment by 0xdabbad00** [comment]
This is expected and correct behavior. The actions you mentioned are not IAM privileges, and therefore Parliament is correct in identifying those as UNKNOWN_ACTION, and you should find AWS's Access Analyzer does the same (or they should).  

The action `s3:GetBucketLifecycle` is granted via the IAM privilege `s3:GetLifecycleConfiguration` (you can click the link on the privilege which will take you to that action: https://docs.aws.amazon.com/service-authorization/latest/reference/list_amazons3.html ).  Similarly `s3:HeadBucket` is an action, and not a privilege. I think the privilege for that action is `s3:ListBucket`.  If you ever see `s3:HeadBucket` in an IAM policy, that policy is wrong.  AWS makes that mistake frequently in their own docs and other resources they put out, and I've gotten them to fix it a number of times.
