### ISSUE TITLE
Incorrect UNKNOWN_ACTION

### ISSUE THREAD

**Issue by rajirchandran** [duo-labs/parliament#195]
The below policy is tagged incorrectly

`{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "denyregistration",
      "Effect": "Deny",
      "Action": [
        "route53domains:RegisterDomain",
        "route53domains:AcceptDomainTransferFromAnotherAwsAccount",
        "route53domains:CancelDomainTransferToAnotherAwsAccount",
        "route53domains:TransferDomain"
      ],
      "Resource": [
        "*"
      ]
    }
  ]
}`

LOW[line:9]: Unknown action - Unknown action route53domains:AcceptDomainTransferFromAnotherAwsAccount
LOW[line:10]: Unknown action - Unknown action route53domains:CancelDomainTransferToAnotherAwsAccount

Please correct this

**Comment by 0xdabbad00** [comment]
This requires updating the IAM data which will happen when https://github.com/duo-labs/parliament/pull/194 is merged.  You can update your own data locally by following the instructions at https://github.com/duo-labs/parliament#updating-the-privilege-info
