### ISSUE TITLE
Incorrect UNKNOWN_ACTION

### ISSUE THREAD

**Issue by rajirchandran** [duo-labs/parliament#200]
The below policy is tagged incorrectly

{ "Version": "2012-10-17", "Statement": [ { "Sid": "denyregistration", "Effect": "Deny", "Action": [ "route53domains:RegisterDomain", "route53domains:AcceptDomainTransferFromAnotherAwsAccount", "route53domains:CancelDomainTransferToAnotherAwsAccount", "route53domains:TransferDomain" ], "Resource": [ "*" ] } ] }

LOW[line:9]: Unknown action - Unknown action route53domains:AcceptDomainTransferFromAnotherAwsAccount
LOW[line:10]: Unknown action - Unknown action route53domains:CancelDomainTransferToAnotherAwsAccount

Even after merging https://github.com/duo-labs/parliament/pull/194, we still see the issue. Please help.
![image](https://user-images.githubusercontent.com/39545379/137246442-eb7aa2c6-1f2c-4424-8da8-0bc7281bf76c.png)

**Comment by 0xdabbad00** [comment]
I don't do a good job of updating parliament.summitroute.com unfortunately.  That site was mostly a demo to show what could be possible. I think this issue just needs to be run locally or maybe update the IAM data again.
