### ISSUE TITLE
Missing sustainability IAM prefix

### ISSUE THREAD

**Issue by everops-matt** [duo-labs/parliament#214]
The IAM definitions in parliament need to be updated with the `sustainability` prefix that was recently added to AWS.

Error:
`LOW - Unknown prefix -  - Unknown prefix sustainability - {'string': 'sustainability:*',` 

[Understanding your customer carbon footprint tool](https://docs.aws.amazon.com/awsaccountbilling/latest/aboutv2/what-is-ccft.html)
You must have the IAM permission `sustainability:GetCarbonFootprintSummary` to access the customer carbon footprint tool and data.

**Comment by 0xdabbad00** [comment]
Should be resolved in https://github.com/duo-labs/parliament/releases/tag/1.6.0 as the IAM data has been updated.
