### ISSUE TITLE
Unknown action logs:TagResource

### ISSUE THREAD

**Issue by dngrtech** [duo-labs/parliament#230]
While running parliament against an IAM policy document it throws an error:
LOW - Unknown action -  - Unknown action logs:TagResource - {'string': 'logs:TagResource', 'line': 1, 'column': 5000, 'filepath': 'test.json'}
However, this action exists according to AWS documentation: https://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/API_TagResource.html
parliament version: 1..6.1

running update_iam_data.py didn't help, this IAM actions doesn't appear in the output.

**Comment by AXL270** [comment]
Same for :
- logs:GetDataProtectionPolicy
- logs:ListTagsForResource
- logs:DescribeAccountPolicies
- logs:DescribeLogGroups
- lambda:GetRuntimeManagementConfig
- lambda:PutRuntimeManagementConfig 
- account:GetAccountInformation
- purchase-orders:GetPurchaseOrder
- purchase-orders:ListPurchaseOrderInvoices 
- purchase-orders:ListPurchaseOrders
- s3:GetAccelerateConfiguration

**Comment by 0xdabbad00** [comment]
Please ensure that reading the update_iam_data.py script replaces the existing `iam_definition.json` and check if that priv exists in there.  I do see it in https://docs.aws.amazon.com/service-authorization/latest/reference/list_amazoncloudwatchlogs.html

**Comment by iainelder** [comment]
#239 fixed this specific instance by adding logs:TagResource to `iam_definition.json`.

#240 added @0xdabbad00 's workaround hint to the README.

But rthe latest release 1.6.2 doesn't include these fixes.

@rjcassara- , can we make a new release?

**Comment by iainelder** [comment]
[Version 1.63](https://github.com/duo-labs/parliament/releases/tag/1.63) just released which includes all the above changes! :heart: 

A project admin can close this now.

**Comment by rjcassara-** [comment]
Release 1.6.3 is up with changes
