### ISSUE TITLE
Markdown scraping vs. html scraping

### ISSUE THREAD

**Issue by jplock** [duo-labs/parliament#27]
Would there be any benefit to scraping the markdown files at https://github.com/awsdocs/iam-user-guide/blob/master/doc_source/reference_policies_actions-resources-contextkeys.md over the HTML version at https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_actions-resources-contextkeys.html ?

**Comment by 0xdabbad00** [comment]
I think for now, the html scraping works well so there isn't a reason to change it.  I also think the  github repos from AWS also tend to lag behind the HTML docs by a few days.  That said, I written the scraping code before I realized there was the markdown on github, so I likely would not have done the web scraping had I known about that. If AWS changes the HTML I may look to use the markdown instead.
