### ISSUE TITLE
RESOURCE_MISMATCH not correct for redshift:GetClusterCredentials

### ISSUE THREAD

**Issue by danielpops** [duo-labs/parliament#32]
It seems like there is a problem with the logic in `is_arn_match`. I ran into an issue with `redshift:GetClusterCredentials`.

Simple repro =>

```
$ parliament --string '
{
    "Statement": [
        {
            "Action": "redshift:GetClusterCredentials",
            "Effect": "Allow",
            "Resource": "arn:aws:redshift:us-west-2:123456789012:dbuser:the_cluster/the_user"
        }
    ],
    "Version": "2012-10-17"
}' --json | jq .
{
  "issue": "RESOURCE_MISMATCH",
  "title": "No resources match for the given action",
  "severity": "MEDIUM",
  "description": "Double check that the actions are valid for the specified resources (and vice versa). See https://iam.cloudonaut.io/reference/ or the AWS docs for details",
  "detail": [
    {
      "action": "redshift:GetClusterCredentials",
      "required_format": "arn:*:redshift:*:*:dbuser:*/*"
    }
  ],
  "location": {
    "actions": [
      "redshift:GetClusterCredentials"
    ],
    "filepath": null
  }
}
```

The expected and actual pattern looks correct to me =>
```
(Pdb) arn_parts
['arn',    '*',   'redshift',          '*',                   '*',              'dbuser',                  '*/*']
(Pdb) resource_parts
['arn', 'aws', 'redshift', 'us-west-2', '123456789012', 'dbuser', 'the_cluster/the_user']
```

All the logic in  `is_arn_match` confuses me. I feel like there could be a simple glob check at the top to circumvent all that custom logic for special things like s3 buckets. However, interestingly, that doesn't work either???

```
>>> fnmatch.fnmatch('arn:*:redshift:*:*:dbuser:*/*', 'arn:aws:redshift:us-west-2:528741615426:dbuser:the_cluster/the_user')
False
```

Which is weird, because translating to regex, then using that does work... 

```
>>> import re
>>> re.match(fnmatch.translate('arn:*:redshift:*:*:dbuser:*/*'), 'arn:aws:redshift:us-west-2:528741615426:dbuser:the_cluster/the_user').group()
'arn:aws:redshift:us-west-2:528741615426:dbuser:the_cluster/the_user'
```

**Comment by 0xdabbad00** [comment]
First, cool to see you using the override functionality! I was confused for a minute where I had mentioned "cloudonaut" in a description until I realized what you did.

Next, yes, the `is_arn_match` function is a disaster due to me needing a function that can find the intersection of two regexes, but none existing that isn't terribly slow, so me trying to hack my way to a solution.

I'll need to test why it doesn't like that string. Nothing immediately jumps out to me.

**Comment by 0xdabbad00** [comment]
Related to #11

**Comment by 0xdabbad00** [comment]
`is_arn_match` has been massively cleaned up thanks to https://github.com/duo-labs/parliament/issues/36#issuecomment-574001764
