### ISSUE TITLE
Feature request: Plugin-like capabilities for checking bad combinations

### ISSUE THREAD

**Issue by kmcquade** [duo-labs/parliament#33]
Hey @0xdabbad00 ,

I was looking at the `check_for_bad_patterns` method and thought that it might be a good idea if Parliament supported some kind of plugin-ish way of developing your own rules in Python. I'm all for submitting PRs, but I think it would help the community contribute a lot more if we were able to add our own rules somehow. I hesitate to make a suggestion on how exactly to do that - but I think it's fair to say that the logic around policy analysis is complex enough that we'd want to express our rules in Python as well. 

Let me know what you think. Happy to collaborate and/or brainstorm with you on this.

**Comment by 0xdabbad00** [comment]
A lot of ideas I would hope would be added directly to Parliament, but I understand some folks might have rules specific to their environment, such as never allow `s3:GetObject` to bucket `supersecret`.   

CloudMapper has this concept, where if you create a `private_commands` directory, that code gets loaded and is made accessible as a command you can run.  Unfortunately this adds half a second to the load time for unknown reasons. https://github.com/duo-labs/cloudmapper/blob/7e0baa57939de735105e25fb4e3c5547ca64f4c7/cloudmapper.py#L51

Similarly if you name that file `custom_auditor.py` it will get loaded by the audit code so you can have your own audit functions or filtering, which is described here: https://github.com/duo-labs/cloudmapper/commit/c6fd62ae124c41e7b140afc58a3e9a1d80e07172#diff-85b5ffec5d4ed4447abc1daffdc5612dR8

I've used that capability of CloudMapper for some private things and it was sufficient for my needs, so I'd apply something similar for this.

I actually have to add some custom functionality for a client by the end of the month, so this aligns well with that. This client wants the ability to fail their CI/CD pipeline for any IAM policy updates that add the ability to change IAM things (ie. they want to restrict privilege escalation paths).  I likely will commit this to master as a low severity alert, but could build this plugin concept as part of it.

**Comment by 0xdabbad00** [comment]
This has been resolved in #40, and a release cut for this as 0.4.0.  See the README for details: https://github.com/duo-labs/parliament#custom-auditors
