### ISSUE TITLE
Write glob intersection library

### ISSUE THREAD

**Issue by 0xdabbad00** [duo-labs/parliament#36]
There needs to be a library written that can check for glob intersections.  Some test cases:
```
[
# string1, string2, whether they match
{"a", "b", False},
{"a", "a", True},
{"a", "*", True},
{"*", "a", True},
{"a*a", "*", True},
{"a*a", "a*b", False},
{"a*a", "aa", True},
{"a*a", "aba", True},
{"*a*", "*b*", True}, # Example "ab"
{"a*a*", "a*b*", True}, # Example "aba"
]
```
This would have better fixed #32 and #11 instead of me endlessly hacking `is_arn_match`

**Comment by 0xdabbad00** [comment]
There is a glob intersection library written in Go that could be translated to Python: https://github.com/Pathgather/glob-intersection

The problem this should solve is described more in the comments at https://github.com/duo-labs/parliament/blob/fdacbf6c82363e1a021a1ff68b4e8ed1ee506aea/parliament/__init__.py#L70

**Comment by ptmcg** [comment]
Will this do?

```
tests = [
    # string1, string2, whether they match
    ("a", "b", False),
    ("a", "a", True),
    ("a", "*", True),
    ("*", "a", True),
    ("a*a", "*", True),
    ("a*a", "a*b", False),
    ("a*a", "aa", True),
    ("a*a", "aba", True),
    ("*a*", "*b*", True), # Example "ab"
    ("a*a*", "a*b*", True), # Example "aba"
]


def is_glob_match(s1, s2):
    if s1 == s2 or s1 == '*' or s2 == '*':
        return True
    if s1[0] == '*' and s2[0] == '*':
        return is_glob_match(s1[1:], s2) or is_glob_match(s1, s2[1:])
    if s1[0] == '*':
        return any(is_glob_match(s1[1:], s2[i:]) for i in range(len(s2)))
    if s2[0] == '*':
        return any(is_glob_match(s1[i:], s2[1:]) for i in range(len(s1)))
    return s1[0] == s2[0] and is_glob_match(s1[1:], s2[1:])


for a, b, expected in tests:
    match = is_glob_match(a, b)
    print(a, b, expected, match, match == expected)

```

**Comment by 0xdabbad00** [comment]
OMG!!! Thank you! I added this code to https://github.com/duo-labs/parliament/pull/51 and got so antsy I cut a release before I remembered to credit you in #52.

**Comment by ptmcg** [comment]
Some additional tests highlight gaps in handling empty strings, and strings with multiple '*'s:

    ("", "*", True),
    ("", "**", True),
    ("", "a", False),
    ("**", "a", True),

Updated code function:

    def is_glob_match(s1, s2):
        if s1 == s2:
            return True
        if s1 and all(c == '*' for c in s1) or s2 and all(c == '*' for c in s2):
            return True
        if not s1 or not s2:
            return False
        if s1[0] == '*' and s2[0] == '*':
            return is_glob_match(s1[1:], s2) or is_glob_match(s1, s2[1:])
        if s1[0] == '*':
            return any(is_glob_match(s1[1:], s2[i:]) for i in range(len(s2)))
        if s2[0] == '*':
            return any(is_glob_match(s1[i:], s2[1:]) for i in range(len(s1)))
        return s1[0] == s2[0] and is_glob_match(s1[1:], s2[1:])

**Comment by 0xdabbad00** [comment]
Good catch! I've pushed a new release with this updated code. Thank you again so much for this.  The old code I had written was such a mess of special cases until your function showed how to do it properly.

**Comment by ptmcg** [comment]
And finally for posterity, maybe some comments...

    def is_glob_match(s1, s2):
        """
        A. if strings are equal, TRUE
        B. if either string is all '*'s, TRUE
        C. if either string is '', FALSE (already handled case if both are '' in A)
        (at this point, we know that both s1 and s2 are non-empty, so safe to access [0]'th element)
        D. if both strings start with '*', TRUE if match first with remainder of second or second with remainder of first
        E. if s1 starts with '*', TRUE if remainder of s1 matches any length remainder of s2
        F. if s2 starts with '*', TRUE if remainder of s2 matches any length remainder of s1
        G. TRUE if s1 and s2 both have same first element and remainder of s1 matches remainder of s2
        """
        # A
        if s1 == s2:
            return True
        # B
        if s1 and all(c == '*' for c in s1) or s2 and all(c == '*' for c in s2):
            return True
        # C
        if not s1 or not s2:
            return False
        # D
        if s1[0] == s2[0] == '*':
            return is_glob_match(s1[1:], s2) or is_glob_match(s1, s2[1:])
        # E
        if s1[0] == '*':
            return any(is_glob_match(s1[1:], s2[i:]) for i in range(len(s2)))
        # F
        if s2[0] == '*':
            return any(is_glob_match(s1[i:], s2[1:]) for i in range(len(s1)))
        # G
        return s1[0] == s2[0] and is_glob_match(s1[1:], s2[1:])

No change in the logic, so no need to push a release with this change, but the breadcrumbs may come in handy some day. (I did make a tiny change in the implementation of D, but the logic is the same.)
