### ISSUE TITLE
support action not recognised

### ISSUE THREAD

**Issue by jmflynn81** [duo-labs/parliament#4]
When testing a policy with the support action defined, the response 
`'INVALID - Unknown action support:*'` is returned. the support action is listed here https://docs.aws.amazon.com/IAM/latest/UserGuide/list_awssupport.html

Steps to reproduce...

```shell
parliament --minimal --string '{"Version":"2012-10-17","Statement": {"Effect": "Allow","Action": "support:*","Resource": "*"}}'
```

parliment version 0.2.4 installed

**Comment by 0xdabbad00** [comment]
This should be resolved in 0.2.5.  AWS only recently documented the `support` prefix and I hadn't updated the IAM definition for a while. Thank you @jmflynn81 !
