### ISSUE TITLE
Feature: Public Auditors

### ISSUE THREAD

**Issue by kmcquade** [duo-labs/parliament#57]
@0xdabbad00 - I love the "Private Auditors" feature. It is really easy to add on new rules.

I'd like to request a "Public Auditors" feature (perhaps just call it "Public Rulesets"?) - where we can add on rulesets to this public repository to be incorporated as part of the package by default. I have a *lot* of tests I'd like to offload from Policy Sentry and move over to here so we can use Parliament as the primary place for static analysis for IAM policies :) 

Also, command line toggling of finding groups and severity types would be legit. Like this:

```
parliament --exclude informational,community,whatevergroup
```

I have quite a few rules I'd like to check in as PRs once this is done.

**Comment by 0xdabbad00** [comment]
Closing this as the community auditors I think satisfies this, and in #83 I added the idea of having tags on findings to more easily exclude them via the command-line.
