### ISSUE TITLE
Provide __is_allowed method as directly callable (i.e., get_allowed_actions)

### ISSUE THREAD

**Issue by kmcquade** [duo-labs/parliament#58]
Scott, it would be helpful if the `__is_allowed` method here was available outside of the `get_allowed_resources` method (see [here](https://github.com/duo-labs/parliament/blob/master/parliament/policy.py#L86)). I like that Parliament considers Conditions etc. when evaluating whether an action is actually allowed or not (whereas in Policy Sentry I just expand the actions and then see if the action is in the list of expanded actions). But it looks like there is no way to just feed in the policy and determine if an action is allowed.

**Comment by 0xdabbad00** [comment]
This makes sense. I've been using `get_allowed_resources` and then checking if the response is empty, but I could put that into a function to do that logic.

**Comment by kmcquade** [comment]
Interesting. I think I misinterpreted what `__is_allowed` does. I thought it basically did this:

https://github.com/salesforce/policy_sentry/blob/master/policy_sentry/util/policy_files.py#L6

Except while understanding the logic of Conditions.

I put together some of this logic already so I'll put together a PR where you can review if this meets our needs for this. It should work.

**Comment by 0xdabbad00** [comment]
There is now a `get_allowed_actions` function: https://github.com/duo-labs/parliament/blob/3a9f711be2f4b5cc0ca3591cac7e76fefe474ec2/parliament/policy.py#L76
