### ISSUE TITLE
Community auditor: sensitive bucket access

### ISSUE THREAD

**Issue by xen0l** [duo-labs/parliament#85]
Now, when community auditor support is available, we should start adding more checks. One of the checks that will be useful is sensitive bucket access. We could use the example from README.md as a baseline, but it would be great if the check supported a way how to specify sensitive buckets, e.g. via config.

**Comment by 0xdabbad00** [comment]
This is going to be out of scope as I don't know of a way to allow people to customize functionality of the custom auditors in a generic way.

**Comment by xen0l** [comment]
@0xdabbad00 I was thinking about this a bit and I would make it more generic, not specitic just to S3 buckets. My idea is simple and relies on implementing a generic check that would read list of sensitive assets from a user-suplied config value. The check would be active by default, but as the default config is going to empty, it won't trigger anything. What do you think about this approach?

**Comment by 0xdabbad00** [comment]
Is the idea that you'd have a config file (maybe just a section of the config.yaml that is used for overriding the rules) to have say:
```
- sensitive_buckets:
  - my_pii
  - my_credit_card_info
```

Then the rule would try to read the array `sensitive_buckets` and if it finds it, then it does the check?

That seems reasonable if you wanted to send a PR.

**Comment by xen0l** [comment]
@0xdabbad00 exactly like that. However, I think that this could be made generic, not specifically tied to S3. This would enable people to configure what assets they consider sensitive and be warned if they are in the policies.
