### ISSUE TITLE
Example using private auditors as a library 

### ISSUE THREAD

**Issue by jplock** [duo-labs/parliament#88]
Is there a way to have a directory of private auditors that lives outside of the parliament folder (I’m using parliament as a library)?

The parliament module name seems hard coded in the import path in policy.py line 267

Thanks for a great library!

**Comment by 0xdabbad00** [comment]
I believe it should be possible to import the private auditors directory as a path referenced from your current working directory.  You can see the `parliament` binary is simply this: https://github.com/duo-labs/parliament/blob/master/bin/parliament

The importing of the private auditoring directory, as you pointed out, is done around here: https://github.com/duo-labs/parliament/blob/f9a2d8e889122c6a060504c972f4a61d7a7310b3/parliament/policy.py#L259

You can try adding some print statements to see what your `sys.path` is.

**Comment by jplock** [comment]
Isn't this line forcing the private auditor modules to be underneath the `parliament` namespace?

https://github.com/duo-labs/parliament/blob/0.4.8/parliament/policy.py#L265

**Comment by 0xdabbad00** [comment]
No, because a few lines down, if a custom path is specified for the private auditors, then it sets `full_package_name` with that path.

https://github.com/duo-labs/parliament/blob/0.4.8/parliament/policy.py#L274

**Comment by jplock** [comment]
Oh duh, you're right, sorry about that.  I'll keep messing around with the path to see if I can get it to work.  Thanks for the help.

**Comment by 0xdabbad00** [comment]
I also just tested by referencing a private auditors directory that is not within my `parliament` directory, and it worked.  Note though that you cannot reference parent directories (ie `../mypath`), because of the `.` in that path.  That can probably be fixed somehow, but it currently won't work.

**Comment by jplock** [comment]
@0xdabbad00 should I be able to pass a relative subdirectory into `private_auditors_custom_path` without a leading `.` or `/`?

**Comment by 0xdabbad00** [comment]
Yes, that should work.
