### ISSUE TITLE
Strip wildcards from "resource type" field in when scraping Actions Table?

### ISSUE THREAD

**Issue by kmcquade** [duo-labs/parliament#9]
It looks like when you scrape the Actions table from the documentation, you don't strip the `*` from the end of the resource types.

https://github.com/duo-labs/parliament/blob/master/utils/update_iam_data.py#L123

When writing policy sentry, I was confused by this too. But I realized that:
(1) the `*` in that table appears to be more of an asterisk indicating "look somewhere else on this page, like click the link, to find out what it means" rather than a wildcard.
(2) It seems like the `*` pattern in those tables in the IAM docs is lazily and inconsistently applied.
(3) Bottom line was that for me, it would mess with my automation.

I am not sure if it is messing with yours, but when debugging Parliament for a separate issue, I saw that it would look for `resource_type = "user*"` here.

![image](https://user-images.githubusercontent.com/3422255/69497559-64692e80-0eac-11ea-9bd5-8d02677c1ba7.png)

I'd submit a PR, but I'm not sure what the after effects of such a change would be, so I'm really just opening up this issue to raise a *possible* concern. Lmk what you think.

**Comment by 0xdabbad00** [comment]
The asterisk on the resource type means that it is required, as shown at the top of the table.  

<img width="808" alt="Screen Shot 2019-11-24 at 2 50 17 PM" src="https://user-images.githubusercontent.com/1979334/69502207-c4ba9900-0ec9-11ea-989d-cd9dad96b250.png">

In the parliament code, I then use this designator to determine where or not I should check for this resource. https://github.com/duo-labs/parliament/blob/a36fc08392d5c50c6742812fe5427d8d00c55fb8/parliament/statement.py#L334

Having the `*` maintained into the `iam_definition.json` file is therefore desired and things are working as expected.
