### ISSUE TITLE
Commnunity auditors don't run in parliament 0.4.8

### ISSUE THREAD

**Issue by xen0l** [duo-labs/parliament#90]
Parliament 0.4.8 does not include config_override.yaml from community_auditors directory, so it is not working as intended. I located a problem, will open a PR during the day.

**Comment by xen0l** [comment]
@0xdabbad00 could we get PR for this merged and new version released ASAP?

**Comment by 0xdabbad00** [comment]
New release created for this and some other improvements from @xen0l https://github.com/duo-labs/parliament/releases/tag/0.4.9
